version: 2
jobs:
  build:
    working_directory: ~/KotlinOnO
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      CODECOV_TOKEN: "c86d1d6e-a5fe-4e87-a0cd-4384b889ff44"
      GNAG_AUTH_TOKEN: "0a459118e795142573fcf19ab7f0a2e9c57813e4"
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - run:
          name: Jacoco
          command: ./gradlew jacocoTestReport
      - run:
          name: Post Jacoco
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: Gnag
          command: bash gnag.sh
      - run:
          name: Post Gnag report
          command: mv -rf app/build/outputs/gnag app/build/reports
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples

